.TH GMERLIN 1 "Dezember 2007" Gmerlin "User Manuals"
.SH NAME
gmerlin
.SH SYNOPSIS
.B gmerlin 
.I [options]
.I [gmls
.I ...]

.SH DESCRIPTION
Gmerlin GUI Player

.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B -help

.RS 2
Print this help message and exit
.RE

.B -help-man

.RS 2
Print this help message as a manual page and exit
.RE

.B -help-texi

.RS 2
Print this help message in texinfo format and exit
.RE

.B -version

.RS 2
Print version info and exit
.RE

