.TH GMERLIN 1 "October 2011" Gmerlin "User Manuals"
.SH NAME
gmerlin
.SH SYNOPSIS
.B gmerlin 
.I [options]
.I [gmls
.I ...]

.SH DESCRIPTION
Gmerlin GUI Player
.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B -help

.RS 2
Print this help message and exit
.RE

.B -help-man

.RS 2
Print this help message as a manual page and exit
.RE

.B -help-texi

.RS 2
Print this help message in texinfo format and exit
.RE

.B -version

.RS 2
Print version info and exit
.RE

.SH ENVIRONMENT VARIABLES
.B GMERLIN_PLAYER_REMOTE_PORT

.RS 2
Default port for the remote control
.RE
.SH FILES
.B ~/.gmerlin/plugins.xml

.RS 2
Cache of the plugin registry (shared by all applicatons)
.RE

.P
.B ~/.gmerlin/player/config.xml

.RS 2
Used for configuration data. Delete this file if you think you goofed
something up.
.RE

.P
.B ~/.gmerlin/player/tree/tree.xml

.RS 2
Media tree is saved here. The albums are saved as separate files in the same
directory.
.RE

.P
