.TH GMERLIN 1 "Dezember 2008" Gmerlin "User Manuals"
.SH NAME
gmerlin
.SH SYNOPSIS
.B gmerlin 
.I [Optionen]
.I [gmls...]

.SH DESCRIPTION
Gmerlin GUI Spieler
.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B -help

.RS 2
Gib diese Hilfe aus und beende
.RE

.B -help-man

.RS 2
Gib diese Hilfe als Manualpage aus und beende
.RE

.B -help-texi

.RS 2
Gib diese Hilfe im texinfo-Format aus und beende
.RE

.B -version

.RS 2
Gib Version aus und beende
.RE

.SH UMGEBUNGSVARIABLEN
.B GMERLIN_PLAYER_REMOTE_PORT

.RS 2
Voreingestellter Port für die Fernbedienung
.RE
.SH DATEIEN
.B ~/.gmerlin/plugins.xml

.RS 2
Zwischenspeicher für die Plugin-Registry (von allen Programmen gemeinsam
benutzt)
.RE

.P
.B ~/.gmerlin/player/config.xml

.RS 2
Wird für Konfigurationsdaten benutzt. Lösche diese Datein, wenn Du meinst
was zerschossen zu haben.
.RE

.P
.B ~/.gmerlin/player/tree/tree.xml

.RS 2
Mediatree wird hier gespeichert. Alben werden als separate Dateien im gleichen
Verzeichnis gespeichert
.RE

.P
