.TH gmerlin_transcoder 1 "November 2007" Gmerlin "User Manuals"
.SH NAME
gmerlin_transcoder
.SH SYNOPSIS
.B gmerlin_transcoder 
.I [options]

.SH DESCRIPTION
GTK multimedia transcoder

Options

.B -p
.I <file>

.RS 2
Load a profile from the given file
.RE

.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B -help

.RS 2
Print this help message and exit
.RE

.B -help_man

.RS 2
Print this help message as a manual page and exit
.RE

.B -help_texi

.RS 2
Print this help message in texinfo format and exit
.RE

.B -version

.RS 2
Print version info and exit
.RE

