.TH GMERLIN_TRANSCODER_REMOTE 1 "March 2012" Gmerlin "User Manuals"
.SH NAME
gmerlin_transcoder_remote
.SH SYNOPSIS
.B gmerlin_transcoder_remote 
.I [options]
.I command

.SH DESCRIPTION
Remote control command for the Gmerlin GUI transcoder

.SH GLOBAL OPTIONS

.B -host
.I <hostname>

.RS 2
Host to connect to, default is localhost
.RE

.B -port
.I <port>

.RS 2
Port to connect to
.RE

.B -launch

.RS 2
Launch new transcoder if necessary
.RE

.SH COMMANDS

.B -addalbum
.I <album_file>

.RS 2
Add album to track list
.RE

.B -add
.I <location>

.RS 2
Add <location> to the track list
.RE

.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B -help

.RS 2
Print this help message and exit
.RE

.B -help-man

.RS 2
Print this help message as a manual page and exit
.RE

.B -help-texi

.RS 2
Print this help message in texinfo format and exit
.RE

.B -version

.RS 2
Print version info and exit
.RE

.SH ENVIRONMENT VARIABLES
.B GMERLIN_TRANSCODER_REMOTE_PORT

.RS 2
Default port for the remote control
.RE
