static struct
  {
  char * iso_639_b;
  char * name;
  }
language_codes[] =
  {
    { "aar", "Afar", },
    { "abk", "Abkhazian", },
    { "ace", "Achinese", },
    { "ach", "Acoli", },
    { "ada", "Adangme", },
    { "afa", "Afro-Asiatic (Other)", },
    { "afh", "Afrihili", },
    { "afr", "Afrikaans", },
    { "aka", "Akan", },
    { "akk", "Akkadian", },
    { "ale", "Aleut", },
    { "alg", "Algonquian languages", },
    { "amh", "Amharic", },
    { "ang", "English, Old (ca. 450-1100)", },
    { "apa", "Apache languages", },
    { "ara", "Arabic", },
    { "arc", "Aramaic", },
    { "arn", "Araucanian", },
    { "arp", "Arapaho", },
    { "art", "Artificial (Other)", },
    { "arw", "Arawak", },
    { "asm", "Assamese", },
    { "ath", "Athapascan languages", },
    { "aus", "Australian languages", },
    { "ava", "Avaric", },
    { "ave", "Avestan", },
    { "awa", "Awadhi", },
    { "aym", "Aymara", },
    { "aze", "Azerbaijani", },
    { "bad", "Banda", },
    { "bai", "Bamileke languages", },
    { "bak", "Bashkir", },
    { "bal", "Baluchi", },
    { "bam", "Bambara", },
    { "ban", "Balinese", },
    { "bas", "Basa", },
    { "bat", "Baltic (Other)", },
    { "bej", "Beja", },
    { "bel", "Belarusian", },
    { "bem", "Bemba", },
    { "ben", "Bengali", },
    { "ber", "Berber (Other)", },
    { "bho", "Bhojpuri", },
    { "bih", "Bihari", },
    { "bik", "Bikol", },
    { "bin", "Bini", },
    { "bis", "Bislama", },
    { "bla", "Siksika", },
    { "bnt", "Bantu (Other)", },
    { "tib", "Tibetan", },
    { "bos", "Bosnian", },
    { "bra", "Braj", },
    { "bre", "Breton", },
    { "btk", "Batak (Indonesia)", },
    { "bua", "Buriat", },
    { "bug", "Buginese", },
    { "bul", "Bulgarian", },
    { "cad", "Caddo", },
    { "cai", "Central American Indian (Other)", },
    { "car", "Carib", },
    { "cat", "Catalan", },
    { "cau", "Caucasian (Other)", },
    { "ceb", "Cebuano", },
    { "cel", "Celtic (Other)", },
    { "cze", "Czech", },
    { "cha", "Chamorro", },
    { "chb", "Chibcha", },
    { "che", "Chechen", },
    { "chg", "Chagatai", },
    { "chk", "Chuukese", },
    { "chm", "Mari", },
    { "chn", "Chinook jargon", },
    { "cho", "Choctaw", },
    { "chp", "Chipewyan", },
    { "chr", "Cherokee", },
    { "chu", "Church Slavic", },
    { "chv", "Chuvash", },
    { "chy", "Cheyenne", },
    { "cmc", "Chamic languages", },
    { "cop", "Coptic", },
    { "cor", "Cornish", },
    { "cos", "Corsican", },
    { "cpe", "Creoles and pidgins, English based (Other)", },
    { "cpf", "Creoles and pidgins, French-based (Other)", },
    { "cpp", "Creoles and pidgins, Portuguese-based (Other)", },
    { "cre", "Cree", },
    { "crp", "Creoles and pidgins (Other)", },
    { "cus", "Cushitic (Other)", },
    { "wel", "Welsh", },
    { "dak", "Dakota", },
    { "dan", "Danish", },
    { "day", "Dayak", },
    { "del", "Delaware", },
    { "den", "Slave (Athapascan)", },
    { "ger", "German", },
    { "dgr", "Dogrib", },
    { "din", "Dinka", },
    { "div", "Divehi", },
    { "doi", "Dogri", },
    { "dra", "Dravidian (Other)", },
    { "dua", "Duala", },
    { "dum", "Dutch, Middle (ca. 1050-1350)", },
    { "dyu", "Dyula", },
    { "dzo", "Dzongkha", },
    { "efi", "Efik", },
    { "egy", "Egyptian (Ancient)", },
    { "eka", "Ekajuk", },
    { "gre", "Greek, Modern (1453-)", },
    { "elx", "Elamite", },
    { "eng", "English", },
    { "enm", "English, Middle (1100-1500)", },
    { "epo", "Esperanto", },
    { "est", "Estonian", },
    { "baq", "Basque", },
    { "ewe", "Ewe", },
    { "ewo", "Ewondo", },
    { "fan", "Fang", },
    { "fao", "Faroese", },
    { "per", "Persian", },
    { "fat", "Fanti", },
    { "fij", "Fijian", },
    { "fin", "Finnish", },
    { "fiu", "Finno-Ugrian (Other)", },
    { "fon", "Fon", },
    { "fre", "French", },
    { "frm", "French, Middle (ca. 1400-1600)", },
    { "fro", "French, Old (842-ca. 1400)", },
    { "fry", "Frisian", },
    { "ful", "Fulah", },
    { "fur", "Friulian", },
    { "gaa", "Ga", },
    { "gay", "Gayo", },
    { "gba", "Gbaya", },
    { "gem", "Germanic (Other)", },
    { "gez", "Geez", },
    { "gil", "Gilbertese", },
    { "gla", "Gaelic (Scots)", },
    { "gle", "Irish", },
    { "glg", "Gallegan", },
    { "glv", "Manx", },
    { "gmh", "German, Middle High (ca. 1050-1500)", },
    { "goh", "German, Old High (ca. 750-1050)", },
    { "gon", "Gondi", },
    { "gor", "Gorontalo", },
    { "got", "Gothic", },
    { "grb", "Grebo", },
    { "grc", "Greek, Ancient (to 1453)", },
    { "grn", "Guarani", },
    { "guj", "Gujarati", },
    { "gwi", "Gwich´in", },
    { "hai", "Haida", },
    { "hau", "Hausa", },
    { "haw", "Hawaiian", },
    { "heb", "Hebrew", },
    { "her", "Herero", },
    { "hil", "Hiligaynon", },
    { "him", "Himachali", },
    { "hin", "Hindi", },
    { "hit", "Hittite", },
    { "hmn", "Hmong", },
    { "hmo", "Hiri Motu", },
    { "scr", "Croatian", },
    { "hun", "Hungarian", },
    { "hup", "Hupa", },
    { "arm", "Armenian", },
    { "iba", "Iban", },
    { "ibo", "Igbo", },
    { "ijo", "Ijo", },
    { "iku", "Inuktitut", },
    { "ile", "Interlingue", },
    { "ilo", "Iloko", },
    { "ina", "Interlingua (International Auxiliary Language Association)", },
    { "inc", "Indic (Other)", },
    { "ind", "Indonesian", },
    { "ine", "Indo-European (Other)", },
    { "ipk", "Inupiaq", },
    { "ira", "Iranian (Other)", },
    { "iro", "Iroquoian languages", },
    { "ice", "Icelandic", },
    { "ita", "Italian", },
    { "jav", "Javanese", },
    { "jpn", "Japanese", },
    { "jpr", "Judeo-Persian", },
    { "kaa", "Kara-Kalpak", },
    { "kab", "Kabyle", },
    { "kac", "Kachin", },
    { "kal", "Kalaallisut", },
    { "kam", "Kamba", },
    { "kan", "Kannada", },
    { "kar", "Karen", },
    { "kas", "Kashmiri", },
    { "geo", "Georgian", },
    { "kau", "Kanuri", },
    { "kaw", "Kawi", },
    { "kaz", "Kazakh", },
    { "kha", "Khasi", },
    { "khi", "Khoisan (Other)", },
    { "khm", "Khmer", },
    { "kho", "Khotanese", },
    { "kik", "Kikuyu", },
    { "kin", "Kinyarwanda", },
    { "kir", "Kirghiz", },
    { "kmb", "Kimbundu", },
    { "kok", "Konkani", },
    { "kom", "Komi", },
    { "kon", "Kongo", },
    { "kor", "Korean", },
    { "kos", "Kosraean", },
    { "kpe", "Kpelle", },
    { "kro", "Kru", },
    { "kru", "Kurukh", },
    { "kum", "Kumyk", },
    { "kur", "Kurdish", },
    { "kut", "Kutenai", },
    { "lad", "Ladino", },
    { "lah", "Lahnda", },
    { "lam", "Lamba", },
    { "lao", "Lao", },
    { "lat", "Latin", },
    { "lav", "Latvian", },
    { "lez", "Lezghian", },
    { "lin", "Lingala", },
    { "lit", "Lithuanian", },
    { "lol", "Mongo", },
    { "loz", "Lozi", },
    { "ltz", "Letzeburgesch", },
    { "lua", "Luba-Lulua", },
    { "lub", "Luba-Katanga", },
    { "lug", "Ganda", },
    { "lui", "Luiseno", },
    { "lun", "Lunda", },
    { "luo", "Luo (Kenya and Tanzania)", },
    { "lus", "lushai", },
    { "mad", "Madurese", },
    { "mag", "Magahi", },
    { "mah", "Marshall", },
    { "mai", "Maithili", },
    { "mak", "Makasar", },
    { "mal", "Malayalam", },
    { "man", "Mandingo", },
    { "map", "Austronesian (Other)", },
    { "mar", "Marathi", },
    { "mas", "Masai", },
    { "mdr", "Mandar", },
    { "men", "Mende", },
    { "mga", "Irish, Middle (900-1200)", },
    { "mic", "Micmac", },
    { "min", "Minangkabau", },
    { "mis", "Miscellaneous languages", },
    { "mac", "Macedonian", },
    { "mkh", "Mon-Khmer (Other)", },
    { "mlg", "Malagasy", },
    { "mlt", "Maltese", },
    { "mnc", "Manchu", },
    { "mni", "Manipuri", },
    { "mno", "Manobo languages", },
    { "moh", "Mohawk", },
    { "mol", "Moldavian", },
    { "mon", "Mongolian", },
    { "mos", "Mossi", },
    { "mao", "Maori", },
    { "may", "Malay", },
    { "mul", "Multiple languages", },
    { "mun", "Munda languages", },
    { "mus", "Creek", },
    { "mwr", "Marwari", },
    { "bur", "Burmese", },
    { "myn", "Mayan languages", },
    { "nah", "Nahuatl", },
    { "nai", "North American Indian", },
    { "nau", "Nauru", },
    { "nav", "Navajo", },
    { "nbl", "Ndebele, South", },
    { "nde", "Ndebele, North", },
    { "ndo", "Ndonga", },
    { "nds", "Low German; Low Saxon; German, Low; Saxon, Low", },
    { "nep", "Nepali", },
    { "new", "Newari", },
    { "nia", "Nias", },
    { "nic", "Niger-Kordofanian (Other)", },
    { "niu", "Niuean", },
    { "dut", "Dutch", },
    { "nno", "Norwegian Nynorsk", },
    { "nob", "Norwegian Bokmål", },
    { "non", "Norse, Old", },
    { "nor", "Norwegian", },
    { "nso", "Sotho, Northern", },
    { "nub", "Nubian languages", },
    { "nya", "Chichewa; Nyanja", },
    { "nym", "Nyamwezi", },
    { "nyn", "Nyankole", },
    { "nyo", "Nyoro", },
    { "nzi", "Nzima", },
    { "oci", "Occitan (post 1500); Provençal", },
    { "oji", "Ojibwa", },
    { "ori", "Oriya", },
    { "orm", "Oromo", },
    { "osa", "Osage", },
    { "oss", "Ossetian; Ossetic", },
    { "ota", "Turkish, Ottoman (1500-1928)", },
    { "oto", "Otomian languages", },
    { "paa", "Papuan (Other)", },
    { "pag", "Pangasinan", },
    { "pal", "Pahlavi", },
    { "pam", "Pampanga", },
    { "pan", "Panjabi", },
    { "pap", "Papiamento", },
    { "pau", "Palauan", },
    { "peo", "Persian, Old (ca. 600-400 b.c.)", },
    { "phi", "Philippine (Other)", },
    { "pli", "Pali", },
    { "pol", "Polish", },
    { "pon", "Pohnpeian", },
    { "por", "Portuguese", },
    { "pra", "Prakrit languages", },
    { "pro", "Provençal, Old (to 1500)", },
    { "pus", "Pushto", },
    { "que", "Quechua", },
    { "raj", "Rajasthani", },
    { "rap", "Rapanui", },
    { "rar", "Rarotongan", },
    { "roa", "Romance (Other)", },
    { "rom", "Romany", },
    { "rum", "Romanian", },
    { "run", "Rundi", },
    { "rus", "Russian", },
    { "sad", "Sandawe", },
    { "sag", "Sango", },
    { "sah", "Yakut", },
    { "sai", "South American Indian (Other)", },
    { "sal", "Salishan languages", },
    { "sam", "Samaritan Aramaic", },
    { "san", "Sanskrit", },
    { "sas", "Sasak", },
    { "sat", "Santali", },
    { "sco", "Scots", },
    { "sel", "Selkup", },
    { "sem", "Semitic (Other)", },
    { "sga", "Irish, Old (to 900)", },
    { "sgn", "Sign Languages", },
    { "shn", "Shan", },
    { "sid", "Sidamo", },
    { "sin", "Sinhalese", },
    { "sio", "Siouan languages", },
    { "sit", "Sino-Tibetan (Other)", },
    { "sla", "Slavic (Other)", },
    { "slo", "Slovak", },
    { "slv", "Slovenian", },
    { "sme", "Northern Sami", },
    { "smi", "Sami languages (Other)", },
    { "smo", "Samoan", },
    { "sna", "Shona", },
    { "snd", "Sindhi", },
    { "snk", "Soninke", },
    { "sog", "Sogdian", },
    { "som", "Somali", },
    { "son", "Songhai", },
    { "sot", "Sotho, Southern", },
    { "spa", "Spanish", },
    { "alb", "Albanian", },
    { "srd", "Sardinian", },
    { "scc", "Serbian", },
    { "srr", "Serer", },
    { "ssa", "Nilo-Saharan (Other)", },
    { "ssw", "Swati", },
    { "suk", "Sukuma", },
    { "sun", "Sundanese", },
    { "sus", "Susu", },
    { "sux", "Sumerian", },
    { "swa", "Swahili", },
    { "swe", "Swedish", },
    { "syr", "Syriac", },
    { "tah", "Tahitian", },
    { "tai", "Tai (Other)", },
    { "tam", "Tamil", },
    { "tat", "Tatar", },
    { "tel", "Telugu", },
    { "tem", "Timne", },
    { "ter", "Tereno", },
    { "tet", "Tetum", },
    { "tgk", "Tajik", },
    { "tgl", "Tagalog", },
    { "tha", "Thai", },
    { "tig", "Tigre", },
    { "tir", "Tigrinya", },
    { "tiv", "Tiv", },
    { "tkl", "Tokelau", },
    { "tli", "Tlingit", },
    { "tmh", "Tamashek", },
    { "tog", "Tonga (Nyasa)", },
    { "ton", "Tonga (Tonga Islands)", },
    { "tpi", "Tok Pisin", },
    { "tsi", "Tsimshian", },
    { "tsn", "Tswana", },
    { "tso", "Tsonga", },
    { "tuk", "Turkmen", },
    { "tum", "Tumbuka", },
    { "tur", "Turkish", },
    { "tut", "Altaic (Other)", },
    { "tvl", "Tuvalu", },
    { "twi", "Twi", },
    { "tyv", "Tuvinian", },
    { "uga", "Ugaritic", },
    { "uig", "Uighur", },
    { "ukr", "Ukrainian", },
    { "umb", "Umbundu", },
    { "und", "Undetermined", },
    { "urd", "Urdu", },
    { "uzb", "Uzbek", },
    { "vai", "Vai", },
    { "ven", "Venda", },
    { "vie", "Vietnamese", },
    { "vol", "Volapük", },
    { "vot", "Votic", },
    { "wak", "Wakashan languages", },
    { "wal", "Walamo", },
    { "war", "Waray", },
    { "was", "Washo", },
    { "wen", "Sorbian languages", },
    { "wol", "Wolof", },
    { "xho", "Xhosa", },
    { "yao", "Yao", },
    { "yap", "Yapese", },
    { "yid", "Yiddish", },
    { "yor", "Yoruba", },
    { "ypk", "Yupik languages", },
    { "zap", "Zapotec", },
    { "zen", "Zenaga", },
    { "zha", "Zhuang", },
    { "chi", "Chinese", },
    { "znd", "Zande", },
    { "zul", "Zulu", },
    { "zun", "Zuni", },
  };
